#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckNr
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EDP_WORK")]
	public partial class EDP_WorkDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertT_CheckNr(T_CheckNr instance);
    partial void UpdateT_CheckNr(T_CheckNr instance);
    partial void DeleteT_CheckNr(T_CheckNr instance);
    #endregion
		
		public EDP_WorkDataContext() : 
				base(global::CheckNr.Properties.Settings.Default.EDP_WORKConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EDP_WorkDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EDP_WorkDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EDP_WorkDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EDP_WorkDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<T_CheckNr> T_CheckNr
		{
			get
			{
				return this.GetTable<T_CheckNr>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_CheckNr")]
	public partial class T_CheckNr : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _S_ID;
		
		private string _S_Name;
		
		private System.Nullable<System.DateTime> _LastTime;
		
		private string _LastMsg;
		
		private System.Data.Linq.Binary _LastImage;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnS_IDChanging(int value);
    partial void OnS_IDChanged();
    partial void OnS_NameChanging(string value);
    partial void OnS_NameChanged();
    partial void OnLastTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnLastTimeChanged();
    partial void OnLastMsgChanging(string value);
    partial void OnLastMsgChanged();
    partial void OnLastImageChanging(System.Data.Linq.Binary value);
    partial void OnLastImageChanged();
    #endregion
		
		public T_CheckNr()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int S_ID
		{
			get
			{
				return this._S_ID;
			}
			set
			{
				if ((this._S_ID != value))
				{
					this.OnS_IDChanging(value);
					this.SendPropertyChanging();
					this._S_ID = value;
					this.SendPropertyChanged("S_ID");
					this.OnS_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_Name", DbType="VarChar(50)")]
		public string S_Name
		{
			get
			{
				return this._S_Name;
			}
			set
			{
				if ((this._S_Name != value))
				{
					this.OnS_NameChanging(value);
					this.SendPropertyChanging();
					this._S_Name = value;
					this.SendPropertyChanged("S_Name");
					this.OnS_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastTime
		{
			get
			{
				return this._LastTime;
			}
			set
			{
				if ((this._LastTime != value))
				{
					this.OnLastTimeChanging(value);
					this.SendPropertyChanging();
					this._LastTime = value;
					this.SendPropertyChanged("LastTime");
					this.OnLastTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastMsg", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string LastMsg
		{
			get
			{
				return this._LastMsg;
			}
			set
			{
				if ((this._LastMsg != value))
				{
					this.OnLastMsgChanging(value);
					this.SendPropertyChanging();
					this._LastMsg = value;
					this.SendPropertyChanged("LastMsg");
					this.OnLastMsgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastImage", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary LastImage
		{
			get
			{
				return this._LastImage;
			}
			set
			{
				if ((this._LastImage != value))
				{
					this.OnLastImageChanging(value);
					this.SendPropertyChanging();
					this._LastImage = value;
					this.SendPropertyChanged("LastImage");
					this.OnLastImageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
